export const deck = [
  {
    id: 1,
    name: 'Aragorn',
    imageUrl: '/images/Aragorn.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 2,
    name: 'Arwen',
    imageUrl: '/images/Arwen.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 3,
    name: 'Beers',
    imageUrl: '/images/Beers.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 4,
    name: 'Boromir',
    imageUrl: '/images/Boromir.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 5,
    name: 'FrodoGandalf',
    imageUrl: '/images/FrodoGandalf.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 6,
    name: 'Galadriel',
    imageUrl: '/images/Galadriel.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 7,
    name: 'Gimli',
    imageUrl: '/images/Gimli.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 8,
    name: 'Gollum',
    imageUrl: '/images/Gollum.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 9,
    name: 'Kuppa',
    imageUrl: '/images/Kuppa.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 10,
    name: 'Legolas',
    imageUrl: '/images/Legolas.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 11,
    name: 'Pippin',
    imageUrl: '/images/Pippin.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 12,
    name: 'Samwise',
    imageUrl: '/images/Samwise.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 13,
    name: 'Aragorn',
    imageUrl: '/images/Aragorn.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 14,
    name: 'Arwen',
    imageUrl: '/images/Arwen.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 15,
    name: 'Beers',
    imageUrl: '/images/Beers.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 16,
    name: 'Boromir',
    imageUrl: '/images/Boromir.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 17,
    name: 'FrodoGandalf',
    imageUrl: '/images/FrodoGandalf.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 18,
    name: 'Galadriel',
    imageUrl: '/images/Galadriel.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 19,
    name: 'Gimli',
    imageUrl: '/images/Gimli.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 20,
    name: 'Gollum',
    imageUrl: '/images/Gollum.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 21,
    name: 'Kuppa',
    imageUrl: '/images/Kuppa.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 22,
    name: 'Legolas',
    imageUrl: '/images/Legolas.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 23,
    name: 'Pippin',
    imageUrl: '/images/Pippin.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
  {
    id: 24,
    name: 'Samwise',
    imageUrl: '/images/Samwise.jpg',
    poster: '/images/Poster.jpg',
    show: false,
  },
];
